/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BL.BL_Persona;
import BL.EnviarCorreo;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author michael
 */
public final class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private DefaultTableModel dtmpersonas;
    private ArrayList<BL_Persona> listaPersonas;
    private TableRowSorter trsfiltro;
    private BL_Persona blp;

    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        //cargar
        cargarPersonas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm_clickderecho = new javax.swing.JPopupMenu();
        mi_editar = new javax.swing.JMenuItem();
        mi_eliminar = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        tp_menu = new javax.swing.JTabbedPane();
        p_personas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_buscarPersona = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_personas = new javax.swing.JTable();
        p_miniterios = new javax.swing.JPanel();
        p_mensaje = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_para = new javax.swing.JTextField();
        tf_asunto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        bt_enviar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        mi_editar.setText("Editar");
        mi_editar.setToolTipText("");
        pm_clickderecho.add(mi_editar);

        mi_eliminar.setText("Eliminar");
        pm_clickderecho.add(mi_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tp_menu.setBackground(new java.awt.Color(51, 51, 51));

        p_personas.setBackground(new java.awt.Color(51, 51, 51));
        p_personas.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");

        tf_buscarPersona.setBackground(new java.awt.Color(51, 51, 51));
        tf_buscarPersona.setForeground(new java.awt.Color(204, 204, 204));
        tf_buscarPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_buscarPersonaKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tb_personas.setBackground(new java.awt.Color(51, 51, 51));
        tb_personas.setForeground(new java.awt.Color(255, 255, 255));
        tb_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_personasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_personas);

        javax.swing.GroupLayout p_personasLayout = new javax.swing.GroupLayout(p_personas);
        p_personas.setLayout(p_personasLayout);
        p_personasLayout.setHorizontalGroup(
            p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_personasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_personasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        p_personasLayout.setVerticalGroup(
            p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_personasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_personasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_buscarPersona, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tp_menu.addTab("Personas", p_personas);

        p_miniterios.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout p_miniteriosLayout = new javax.swing.GroupLayout(p_miniterios);
        p_miniterios.setLayout(p_miniteriosLayout);
        p_miniteriosLayout.setHorizontalGroup(
            p_miniteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        p_miniteriosLayout.setVerticalGroup(
            p_miniteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        tp_menu.addTab("Miniterios", p_miniterios);

        p_mensaje.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Para");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Asunto");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane2.setViewportView(ta_mensaje);

        bt_enviar.setText("Enviar");
        bt_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_mensajeLayout = new javax.swing.GroupLayout(p_mensaje);
        p_mensaje.setLayout(p_mensajeLayout);
        p_mensajeLayout.setHorizontalGroup(
            p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mensajeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_para, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(p_mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mensajeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_enviar)))
                .addContainerGap())
        );
        p_mensajeLayout.setVerticalGroup(
            p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mensajeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_asunto)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_enviar)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        tp_menu.addTab("Mensaje", p_mensaje);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_menu)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_menu)
        );

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_buscarPersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarPersonaKeyReleased
        // TODO add your handling code here:
        filtrar();
        tb_personas.setRowSorter(trsfiltro);
    }//GEN-LAST:event_tf_buscarPersonaKeyReleased

    private void tb_personasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_personasMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            int numero_fila = tb_personas.rowAtPoint(evt.getPoint());
            ListSelectionModel lsm = tb_personas.getSelectionModel();
            lsm.setSelectionInterval(numero_fila, numero_fila);
            pm_clickderecho.show(evt.getComponent(), evt.getX(), evt.getY());
        } else {
            if (evt.getClickCount() >= 2) {
                int fila = tb_personas.getSelectedRow();
                verPersona(fila);
            }
        }
    }//GEN-LAST:event_tb_personasMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AgregarPersona ag = new AgregarPersona(this, rootPaneCheckingEnabled, null);
        ag.setVisible(true);
        if(ag.actualizar){
            cargarPersonas();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarActionPerformed
        // TODO add your handling code here:
        String mensaje = ta_mensaje.getText();
        String para = tf_para.getText();
        String asunto = tf_asunto.getText();
        
        
    }//GEN-LAST:event_bt_enviarActionPerformed
    
    
    //Buscar Persona segun id
    public void verPersona(int row){
        int idPersona = Integer.parseInt(""+(tb_personas.getValueAt(row, 0)));
        blp = blp.personaPorId(idPersona, listaPersonas);
        AgregarPersona ag = new AgregarPersona(this, rootPaneCheckingEnabled, blp);
        ag.setVisible(true);
    }
    
    //filtro busqueda sencible
    public void filtrar() {
        String hilera = tf_buscarPersona.getText();
        if (!hilera.isEmpty() && hilera.charAt(0) >= 97) {
            hilera = (char) ((hilera.charAt(0) - 32)) + hilera.substring(1);
        }
        trsfiltro.setRowFilter(RowFilter.regexFilter(hilera, 1));
    }

    //Metodos para cargar los datos necesarios
    public void cargarPersonas() {
        blp = new BL_Persona();
        listaPersonas = blp.cargarPersonas();
        formatoTablaPersonas();
    }

    //Metodo definir formato de tablas
    public void formatoTablaPersonas() {

        String[] nombreColumnas = {"id","Nombre", "Primer Apellido", "Segundo Apellido"};
        dtmpersonas = new DefaultTableModel(null, nombreColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        if (!listaPersonas.isEmpty()) {
            for (BL_Persona persona : listaPersonas) {
                dtmpersonas.addRow(new Object[]{persona.getIdPersona(),persona.getNombre(), persona.getPrimerApellido(),
                    persona.getSegundoApellido()});
            }
        }
        tb_personas.setModel(dtmpersonas);
        tb_personas.getColumnModel().getColumn(0).setMinWidth(0);
        tb_personas.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_personas.getColumnModel().getColumn(0).setWidth(0);
        trsfiltro = new TableRowSorter(tb_personas.getModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mi_editar;
    private javax.swing.JMenuItem mi_eliminar;
    private javax.swing.JPanel p_mensaje;
    private javax.swing.JPanel p_miniterios;
    private javax.swing.JPanel p_personas;
    private javax.swing.JPopupMenu pm_clickderecho;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTable tb_personas;
    private javax.swing.JTextField tf_asunto;
    private javax.swing.JTextField tf_buscarPersona;
    private javax.swing.JTextField tf_para;
    private javax.swing.JTabbedPane tp_menu;
    // End of variables declaration//GEN-END:variables
}
